# START

In [4]:
import numpy as np


In [5]:
listas = [5, 3, 1, 7 ,9]
listas

[5, 3, 1, 7, 9]

# MASYVAS

In [7]:
masyvas = np.array(listas)
masyvas

array([5, 3, 1, 7, 9])

In [14]:
eile = np.arange(5, 15, 3)
eile

array([ 5,  8, 11, 14])

In [15]:
nuliai = np.zeros(10)
nuliai

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

# MATRICA

In [12]:
pirminis_listas = [[1, 2 ,3], [6, 5, 4], [8, 9, 7]]
matrica = np.array(pirminis_listas)
matrica

array([[1, 2, 3],
       [6, 5, 4],
       [8, 9, 7]])

In [17]:
np.zeros((5,5), int)

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]])

In [23]:
np.ones(10, int)

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

In [30]:
dast =np.linspace(0, 10 ,5)
dast

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [31]:
np.eye(9)

array([[1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1.]])

# RANDOM ARRAY

In [33]:
np.random.rand(10)

array([0.86629836, 0.01494507, 0.60407223, 0.56042983, 0.99651163,
       0.86447347, 0.45515423, 0.24619426, 0.78179329, 0.37275577])

In [34]:
np.random.randint(100, 200, (7,7))

array([[117, 173, 181, 118, 122, 158, 141],
       [157, 194, 125, 133, 114, 152, 123],
       [111, 198, 156, 156, 120, 145, 151],
       [198, 192, 144, 100, 110, 177, 193],
       [160, 137, 113, 169, 199, 131, 177],
       [191, 174, 103, 135, 143, 132, 125],
       [178, 168, 186, 107, 136, 154, 179]])

# MASYVU PERTVARKYMAS

In [35]:
ilgas64 = np.random.randint(10, 100, 64)
ilgas64

array([57, 13, 28, 96, 74, 48, 45, 81, 91, 59, 13, 35, 13, 95, 38, 48, 84,
       80, 43, 49, 95, 18, 26, 99, 66, 98, 19, 28, 44, 71, 87, 34, 79, 94,
       82, 60, 38, 22, 66, 75, 97, 20, 97, 19, 13, 41, 33, 51, 70, 59, 75,
       78, 63, 63, 71, 21, 80, 44, 11, 66, 49, 67, 34, 80])

In [36]:
print(ilgas64)

[57 13 28 96 74 48 45 81 91 59 13 35 13 95 38 48 84 80 43 49 95 18 26 99
 66 98 19 28 44 71 87 34 79 94 82 60 38 22 66 75 97 20 97 19 13 41 33 51
 70 59 75 78 63 63 71 21 80 44 11 66 49 67 34 80]


In [39]:
matrica8x8 = ilgas64.reshape(8,8)
matrica8x8

array([[57, 13, 28, 96, 74, 48, 45, 81],
       [91, 59, 13, 35, 13, 95, 38, 48],
       [84, 80, 43, 49, 95, 18, 26, 99],
       [66, 98, 19, 28, 44, 71, 87, 34],
       [79, 94, 82, 60, 38, 22, 66, 75],
       [97, 20, 97, 19, 13, 41, 33, 51],
       [70, 59, 75, 78, 63, 63, 71, 21],
       [80, 44, 11, 66, 49, 67, 34, 80]])

# Naudingi metodai

In [40]:
matrica8x8.min()

11

In [41]:
matrica8x8.max()

99

In [43]:
matrica8x8.argmin(axis=0)

array([0, 0, 7, 5, 1, 2, 2, 6], dtype=int64)

# UZDUOTYS

In [47]:
array_1 = np.arange(1, 10)
array_1

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
nuliai = np.zeros(10)
nuliai

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [49]:
viens = np.ones(10)
viens

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [51]:
ketr = np.repeat(float(4), 10)
ketr

array([4., 4., 4., 4., 4., 4., 4., 4., 4., 4.])

In [53]:
lyginiai = np.arange(0, 102, 2)
lyginiai

array([  0,   2,   4,   6,   8,  10,  12,  14,  16,  18,  20,  22,  24,
        26,  28,  30,  32,  34,  36,  38,  40,  42,  44,  46,  48,  50,
        52,  54,  56,  58,  60,  62,  64,  66,  68,  70,  72,  74,  76,
        78,  80,  82,  84,  86,  88,  90,  92,  94,  96,  98, 100])

In [58]:
matrica25 = np.arange(1, 26).reshape(5,5)
matrica25

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [59]:
matrica25[2,1]

12

In [60]:
matrica25[4]

array([21, 22, 23, 24, 25])

In [77]:
matrica25[:3,:3]

array([[ 1,  2,  3],
       [ 6,  7,  8],
       [11, 12, 13]])

In [79]:
matrica25[3:,:3]

array([[16, 17, 18],
       [21, 22, 23]])

In [83]:
random20 = np.random.rand(20)
random20

array([0.60170226, 0.35982385, 0.23443488, 0.57125153, 0.65930749,
       0.76748599, 0.51466821, 0.35116916, 0.71499264, 0.12352146,
       0.69588354, 0.93904983, 0.77183648, 0.35126554, 0.95975257,
       0.6457718 , 0.02545994, 0.93172324, 0.75325826, 0.89189315])

In [86]:
maximumas = random20.max()

0.9597525676973953

In [94]:
maximumas = random20.max()
np.argmax(maximumas)

0

In [89]:
random20.min()

0.02545993527213586

In [95]:
minimumas = random20.min()
np.argmin(minimumas)

0

In [96]:
random20.dtype

dtype('float64')

In [102]:
nr90 = np.arange(1, 101)
nr90[nr90>90]

array([ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [103]:
np.arange(0, 102, 7)

array([ 0,  7, 14, 21, 28, 35, 42, 49, 56, 63, 70, 77, 84, 91, 98])

In [155]:
dast = np.arange(1, 41).reshape(5,8)
dast/40

array([[0.025, 0.05 , 0.075, 0.1  , 0.125, 0.15 , 0.175, 0.2  ],
       [0.225, 0.25 , 0.275, 0.3  , 0.325, 0.35 , 0.375, 0.4  ],
       [0.425, 0.45 , 0.475, 0.5  , 0.525, 0.55 , 0.575, 0.6  ],
       [0.625, 0.65 , 0.675, 0.7  , 0.725, 0.75 , 0.775, 0.8  ],
       [0.825, 0.85 , 0.875, 0.9  , 0.925, 0.95 , 0.975, 1.   ]])

In [165]:
was = np.arange(2, 32).reshape(5,6)
was*was

array([[  4,   9,  16,  25,  36,  49],
       [ 64,  81, 100, 121, 144, 169],
       [196, 225, 256, 289, 324, 361],
       [400, 441, 484, 529, 576, 625],
       [676, 729, 784, 841, 900, 961]])

In [167]:
kintamas = np.arange(1, 101)
kintamas

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [169]:
 nauja_funkcija = np.vectorize(kintamas)
 nauja_funkcija